Update

diff --git a/glibc/armv6h/usr/bin/asl b/glibc/armv6h/usr/bin/asl
--- a/glibc/armv6h/usr/bin/asl
+++ b/glibc/armv6h/usr/bin/asl
@@ -2,10 +2,18 @@
 #!/data/data/com.termux/files/usr/bin/bash
 #
 
+if [[ ! -d /data/data/com.termux/files/usr/lib/conlib ]]; then
+  echo 'error: conlib directory not found.'
+  exit 2
+fi
+
 if [[ -z $* ]]; then
+  echo "$0 [COMMAND]"
   echo 'The command making access to the conlib libraries.'
-  echo 'asl [COMMAND]'
+  echo 'glibc v2.32-2 armv6h'
+  echo 'official site: https://www.gnu.org/software/libc'
+  echo 'GNU site: https://www.gnu.org'
 else
-  export LD_LIBRARY_PATH="/data/data/com.termux/files/usr/lib/conlib:/data/data/com.termux/files/usr/lib"
+  export LD_LIBRARY_PATH="/data/data/com.termux/files/usr/lib/con>
   $*
 fi
